version: '3.8'
services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: javas-db
    ports:
      - "5492:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  gradle-app:
    image: gradle:7.6-jdk17
    container_name: gradle-app
    working_dir: /app
    volumes:
      - ./app:/app
      - gradle_cache:/home/gradle/.gradle
    command: gradle bootRun
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  gradle_cache:
